### ISSUE TITLE
Wildwood dungeon // Andesite structure replaced with granite on press of the button

### ISSUE THREAD

**Issue by Piepower483** [Divine-Journey-2/Divine-Journey-2#467]
**Modpack version:**
2.7.0

**Description:**
In the Wildwood dungeon where you have to copy the andesite structures there is some kind of problem with the command blocks. When I build the structure and press the button, on the site that was prebuilt 2 of the blocks becomes granite. You have to place those 2 granite blocks on the side that the player has to build for the puzzle to be completed.

**Steps to reproduce:**
Get into the wildwood dimension / Find a dungeon / Get to the copy puzzle room / build the andesite structure / press the button / 2 blocks of granite has been replaced / place those 2 granite blocks on the side that the player built / complete the puzzle by pressing the button again

**Expected behavior:**
Expected behaviour is to build the andesite structure and press the button to complete the puzzle, thus not having to replace 2 blocks with granite 

**Screenshots:**
![2021-10-16_14 57 03](https://user-images.githubusercontent.com/12442805/137589078-1b26a596-6afb-45c6-a7ac-33677e06d846.png)
**Additional context:**
Nothing more to say

**Comment by KleinGrrmpf** [comment]
Isn't that the point of the puzzle?

**Comment by Piepower483** [comment]
> Isn't that the point of the puzzle?

Not it is not I would assume. You only get the andesite which is enough to build the structure. You don't get at any point any granite so I would assume that it is not intentional and that this is a bug

**Comment by KleinGrrmpf** [comment]
But you can just mine the granite, replace it with the andesite you got, repress the button (which makes the andesite you placed back into granite) and place the granite you mine on the other side. This way the structures are identical and the door should open.

**Comment by Atricos** [comment]
I assume someone or something has messed with the solution of the puzzle.

Questions:
- Are you playing in Singleplayer or Multiplayer?
- Can you give me the exact world seed and coordinates of the dungeon in Wildwood?

**Comment by Piepower483** [comment]
> I assume someone or something has messed with the solution of the puzzle.
> 
> Questions:
> 
> * Are you playing in Singleplayer or Multiplayer?
> * Can you give me the exact world seed and coordinates of the dungeon in Wildwood?

Playing on singleplayer

Seed: 6156857076120535623

Dimension: Wildwood
Coordinates: 42 76 1034

Just tell me if you need more information

**Comment by WaitingIdly** [comment]
I suspect this bug may be due to Underground Biomes replacing the Andesite Blocks with its custom worldgen. This would have been resolved as of 2.16.0 due to disabling UB in dimensions other than the Overworld.
Would anyone be able to confirm that it does still happen?

**Comment by WaitingIdly** [comment]
no confirmation, couldnt reproduce

**Comment by osimon8** [comment]
I can confirm that this was happening as late as 2.15.0, for reference. Happened to me with granite

**Comment by Preta-Crowz** [comment]
> I can confirm that this was happening as late as 2.15.0, for reference. Happened to me with granite

this was resolved on 2.16, so 2.15 will have this but only there.

**Comment by FakeDomi** [comment]
Still happens in 2.19.4 
![2023-09-05_00 14 29](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/1492543/03f0ed61-16f3-4144-b933-4ddf250db194)

**Comment by Preta-Crowz** [comment]
> The world was generated in that version.
Which one? 2.19.4? pr 2.15.0?

**Comment by FakeDomi** [comment]
2.19.4 - clarified that.

**Comment by DJJBanx** [comment]
Why was this closed? It still happens

Version 2.20.0
Seed -6044818080693993037

![2023-09-24_10 17 58](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/17753420/02c1d721-fe87-48e1-b0f7-09fdec0f1a52)
